#!/usr/bin/env python3
"""
Build src/ui/font.css: the embedded readout typeface.

    python3 tools/mkfont.py

Fetches Oswald (SIL Open Font License 1.1), subsets it to the characters this
HUD can actually print, FORCES ITS FIGURES TABULAR, and writes an @font-face
with the result inlined as a data URI. The game ships as one self-contained
file with no network at runtime, so the font has to travel inside it.

---- why the figures have to be rebuilt, and not just requested ----

The stylesheet asks for tabular figures the correct way -- `font-variant-
numeric: tabular-nums` plus `font-feature-settings: "tnum" 1` -- and on this
face that is a NO-OP, because Oswald ships no `tnum` feature at all. Its
digit advances run 378 to 517 units, a 37% spread between "1" and "0".

That matters more here than in most places. A race clock is rewritten sixty
times a second; with proportional figures every tick changes the string's
width, so the number jitters and the plate it sits in reflows around it. The
previous system-font stack got away with declaring tabular figures only
because the fallback happened to be duplexed already -- the declaration was
doing nothing and nobody could tell.

So this script does what the missing feature would have done: every digit is
given the widest digit's advance, and its outline is translated right by half
the difference so it sits optically centred in that slot. The result is a font
whose figures are tabular by construction, with no feature to negotiate and
nothing for a renderer to ignore.

The family is renamed on the way out. It is a modified font, and shipping a
modification under the original name would misrepresent it.
"""
import base64
import io
import re
import sys
import urllib.request

from fontTools.ttLib import TTFont
from fontTools import subset

CSS_URL = 'https://fonts.googleapis.com/css2?family=Oswald:wght@400..700'
UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/120 Safari/537.36'

# Everything the HUD can print. Arrows are deliberately absent: Oswald has no
# arrow glyphs, so the CSS stack falls through to the system font for those.
CHARS = ('0123456789'
         'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
         'abcdefghijklmnopqrstuvwxyz'
         " :.,/+-·—–%'()")

FAMILY = 'MRCond'


def fetch(url, **hdrs):
    req = urllib.request.Request(url, headers={'User-Agent': UA, **hdrs})
    return urllib.request.urlopen(req).read()


def latin_url():
    css = fetch(CSS_URL).decode()
    for block in re.findall(r'@font-face \{(.*?)\}', css, re.S):
        # The latin block is the one whose unicode-range starts at U+0000.
        if 'U+0000' in block:
            return re.search(r'url\((https://[^)]+)\)', block).group(1)
    raise SystemExit('could not find the latin subset in the served CSS')


def make_tabular(font):
    """Give every digit the widest digit's advance, outline centred in it."""
    cmap = font.getBestCmap()
    glyf, hmtx = font['glyf'], font['hmtx']
    names = [cmap[ord(d)] for d in '0123456789']
    target = max(hmtx[g][0] for g in names)
    moved = 0
    for g in names:
        adv, lsb = hmtx[g]
        shift = (target - adv) // 2
        if shift:
            glyph = glyf[g]
            if glyph.numberOfContours:
                # Translating the base outline is safe under a variable axis:
                # gvar stores deltas relative to these points, so they follow.
                glyph.coordinates.translate((shift, 0))
                glyph.recalcBounds(glyf)
            moved += 1
        hmtx[g] = (target, lsb + shift)
    return target, moved


def main():
    url = latin_url()
    raw = fetch(url)
    font = TTFont(io.BytesIO(raw))

    opts = subset.Options(flavor='woff2', notdef_outline=False,
                          layout_features=['kern', 'liga', 'locl'],
                          recalc_bounds=True)
    sub = subset.Subsetter(options=opts)
    sub.populate(text=CHARS)
    sub.subset(font)

    width, moved = make_tabular(font)
    # Rename: this is a modified font and must not travel as the original.
    for rec in font['name'].names:
        if rec.nameID in (1, 3, 4, 6, 16):
            try:
                cur = rec.toUnicode()
            except Exception:
                continue
            rec.string = cur.replace('Oswald', FAMILY)

    buf = io.BytesIO()
    font.flavor = 'woff2'
    font.save(buf)
    data = buf.getvalue()

    b64 = base64.b64encode(data).decode()
    css = (
        "/* GENERATED BY tools/mkfont.py -- DO NOT EDIT BY HAND.\n"
        " *\n"
        " * Oswald, SIL Open Font License 1.1, modified and renamed: subset to\n"
        " * the characters this HUD prints, and its figures rebuilt tabular\n"
        " * because Oswald ships no tnum feature and its digit advances span\n"
        " * 378-517 units. Every digit now advances %d with the outline centred,\n"
        " * so the race clock cannot reflow as it ticks.\n"
        " *\n"
        " * Variable weight axis 400-700. Arrow glyphs are deliberately absent;\n"
        " * the CSS stack falls through to the system font for those.\n"
        " */\n"
        "@font-face{font-family:'%s';font-style:normal;font-weight:400 700;"
        "font-display:block;src:url(data:font/woff2;base64,%s) format('woff2');}\n"
        % (width, FAMILY, b64)
    )
    with open('src/ui/font.css', 'w') as fh:
        fh.write(css)

    print('digits normalised to advance %d (%d outlines shifted)' % (width, moved))
    print('woff2 %.1f KB -> src/ui/font.css %.1f KB'
          % (len(data) / 1024, len(css) / 1024))


if __name__ == '__main__':
    sys.exit(main())
